#!/bin/bash

echo "🚀 Camera Rental Backend Deployment Helper"
echo "=========================================="

echo ""
echo "📋 Pre-deployment checklist:"
echo "1. Make sure you have a MongoDB Atlas database"
echo "2. Get your MongoDB connection string"
echo "3. Generate a secure JWT secret"
echo "4. Have your GitHub repository ready"
echo ""

echo "🔧 Backend is ready for deployment!"
echo ""
echo "📝 Next steps:"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New' → 'Blueprint'"
echo "4. Connect your GitHub repository"
echo "5. Render will automatically detect the render.yaml file"
echo "6. Add environment variables:"
echo "   - MONGODB_URL=your_mongodb_connection_string"
echo "   - JWT_SECRET=your_secure_jwt_secret"
echo "   - CORS_ORIGIN=http://localhost:5173 (update after frontend deployment)"
echo ""
echo "✅ Backend package.json has been updated with start script"
echo "✅ CORS configuration updated to use environment variables"
echo "✅ render.yaml file created for Render deployment"
echo ""
echo "🎯 After deployment, you'll get a URL like: https://your-app.onrender.com"
echo "   Use this URL to update your frontend API calls" 