services:
  - type: web
    name: camera-rental-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
      - key: JWT_SECRET
      - key: CORS_ORIGIN
        value: http://localhost:5173 