services:
  - type: web
    name: camera-rental-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: http://localhost:5173 